### ISSUE TITLE
 error in PyBluez setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by scenaristeur** [eliasweingaertner/peripage-A6-bluetooth#9]
I got this error in linux Mint

```
pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting PyBluez==0.23
  Downloading PyBluez-0.23.tar.gz (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 KB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyBluez setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Could it be related to https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2 ?

**Comment by ruapho** [comment]
Install pybluez version 0.30 `pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez` and change requirements.txt to `pyBluez==0.30`

https://github.com/pybluez/pybluez/issues/446
https://github.com/pybluez/pybluez/issues/459

**Comment by AntonioMembrino** [comment]
hi. I'm trying to install via pip and with command  pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez...
both comands fails.
I have  download the pybluez's github master branch, when i instal with the comand ### python setup.py install  
gives me this error .....
Local\Programs\Python\Python39\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

**Comment by ruapho** [comment]
> hi. I'm trying to install via pip and with command pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez... both comands fails. I have download the pybluez's github master branch, when i instal with the comand ### python setup.py install gives me this error ..... Local\Programs\Python\Python39\lib\shlex.py", line 140, in read_token nextchar = self.instream.read(1) AttributeError: 'list' object has no attribute 'read'

You might want to ask this over at https://github.com/pybluez/pybluez/issues

**Comment by eliasweingaertner** [comment]
Sorry for the super-late response. Unfortunately the pybluez team has released an updated version in a long time. I just upgraded the requirements.txt to use their master branch in the latest commit (188df13790c4b4a96205c28c83cc1b01e0020ef8)

This solves this problem.

**Comment by eliasweingaertner** [comment]
Fixed with latest commit
